### ISSUE TITLE
bug on printstring();

### ISSUE THREAD

**Issue by codelamana** [adafruit/ST7565-LCD#8]
I tried to run the display on my teensy 3.6 and print strings on the display. it works fine except for that it leaves out the first letter of the string all the. i already recompiled it with the latest files from the repo but didnt fix it. only thing that fixes it, is clearing the display before printing the string

**Comment by dd5xl** [comment]
This looks like a timing problem when sending the 1st character to a page. In SPI mode there is no possibility to check the LCD's busy flag, so specified timing must be maintained properly by the host program.
As the lib has been initially designed for AVR MCUs at 16MHz, I guess your Teensy is way too fast in writing to the SPI.
